## Logistic Regression Exercise

1) Load iris datasets from iris-data-clean.csv
   Replace the values in the columns 'Class' as follows:
     "Setosa" = 0
     "Virginica" = 1
     "Versicolor" = 2
2) Using Logistic Regression, classify the outcome (Column : 'Class') based on the labels (Columns :'sepal length /cm', 'sepal width /cm', 'petal length /cm', 'petal width /cm')
    a) Provide some values to predict the outcome
    b) Validate the model - print the confusion matrix and the accuracy score
3) Redo the above steps with any two **features
    a) Compare the accuracy score with the model built in the above with four features

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

/Users/kyle/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/__init__.py:21: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.21.5)
  from scipy.sparse import issparse


In [2]:
df = pd.read_csv('iris-data-clean.csv')
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm   class
0              5.1             3.5              1.4             0.2  Setosa
1              4.9             3.0              1.4             0.2  Setosa
2              4.7             3.2              1.3             0.2  Setosa
3              4.6             3.1              1.5             0.2  Setosa
4              5.0             3.6              1.4             0.2  Setosa

In [ ]:
print(df['class'].unique())  #check if there are other class except 'setosa', 'virginica' and 'versicolor'

['Setosa' 'Versicolor' 'Virginica']


In [5]:
# if there are other class
#data = df[df['class'].isin(['Setosa', 'Virginica'])].copy()
df['class'] = df['class'].replace({'Setosa': 0, 'Virginica': 1, 'Versicolor': 2})

In [6]:
logReg = LogisticRegression()
x = df[['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm']]
y = df['class']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
logReg.fit(x_train,y_train)

/Users/kyle/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

a) Predict the outcome

In [11]:


print(logReg.predict([[5.1, 3.5, 1.4, 0.2]]))



[0]


/Users/kyle/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


b) validate model( print accuracy_score and confusion matrix)

In [15]:
from sklearn.metrics import accuracy_score

y_pred = logReg.predict(x_test)
acc=accuracy_score(y_test, y_pred)
print(acc)


from sklearn.metrics import confusion_matrix

print(confusion_matrix (y_test, y_pred))
#print(confusion_matrix (y_test, y_pred, labels = [1,0])) # Switching the class 0 and 1

0.9310344827586207
[[ 8  0  0]
 [ 0 10  1]
 [ 0  1  9]]
